# Generated by Django 3.0.4 on 2020-03-22 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=31)),
                ('data_nasterii', models.DateField()),
                ('tel', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=255)),
                ('descriere', models.CharField(max_length=255)),
                ('pret', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tranzactie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_tranz', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tema3.Client')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tema3.Produs')),
            ],
        ),
    ]
