# Generated by Django 3.0.4 on 2020-03-24 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tema3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=25)),
                ('photo', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='tranzactie',
            name='client',
        ),
        migrations.RemoveField(
            model_name='tranzactie',
            name='produs',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Produs',
        ),
        migrations.DeleteModel(
            name='Tranzactie',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tema3.User'),
        ),
        migrations.AddField(
            model_name='comm',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tema3.Post'),
        ),
        migrations.AddField(
            model_name='comm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tema3.User'),
        ),
    ]
