# Generated by Django 3.0.4 on 2020-03-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tema3', '0002_auto_20200324_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=models.DateTimeField(), max_length=120),
        ),
    ]
