# Generated by Django 3.0.4 on 2020-03-25 00:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_tema3', '0003_auto_20200325_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='comm',
            name='text',
            field=models.TextField(default='No message.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default=datetime.datetime(2020, 3, 25, 0, 24, 22, 924613, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
