# Generated by Django 3.0.4 on 2020-03-26 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_tema3', '0004_auto_20200325_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='comm',
            name='name',
            field=models.CharField(default='The Blond User', max_length=25),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='The Blond User', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default=datetime.datetime(2020, 3, 26, 14, 18, 8, 13846, tzinfo=utc), max_length=100),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
