# Generated by Django 3.0.4 on 2020-03-27 01:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_tema3', '0006_auto_20200327_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comm',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 1, 40, 0, 212067, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comm',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 1, 40, 0, 211031, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default=datetime.datetime(2020, 3, 27, 1, 40, 0, 211125, tzinfo=utc), max_length=100),
        ),
    ]
