# Generated by Django 3.0.4 on 2020-03-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tema3', '0008_auto_20200327_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('post', models.ManyToManyField(to='app_tema3.Post')),
            ],
        ),
    ]
